apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: house-prices-app-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jmonsalverodilla/Python-Microservices-Web-App.git
    targetRevision: HEAD
    path: k8s_deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: house-prices-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true