apiVersion: v1
kind: Namespace
metadata:
  name: house-prices-app
  labels:
    name: house-prices-app

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: house-prices-app-config
  namespace: house-prices-app
data:
  frontend_port: "4000"
  backend_port: "5000"
  backend_service: "backend-service"
  postgres_user: "javier"
  postgres_password: "123"
  postgres_db: "testdb"
  postgres_db_host: "postgres-service"
  postgres_db_port: "5432"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: house-prices-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: postgres-deploy
  namespace: house-prices-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: jmr96registry.azurecr.io/postgres:12-alpine
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: house-prices-app-config
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: house-prices-app-config
              key: postgres_password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: house-prices-app-config
              key: postgres_db
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data-storage-volume
            subPath: postgres

#        livenessProbe:
#          exec:
#            command:
#              - pg_isready
#              - -d
#              - testdb
#              - -h
#              - localhost
#              - -U
#              - javier
#          initialDelaySeconds: 30
#          timeoutSeconds: 5
#        readinessProbe:
#          exec:
#            command:
#              - pg_isready
#              - -d
#              - testdb
#              - -h
#              - localhost
#              - -U
#              - javier
#          initialDelaySeconds: 25
#          timeoutSeconds: 1
      volumes:
        - name: data-storage-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: house-prices-app
spec:
  selector:
    app: postgres
  ports:
    - protocol: "TCP"
      port: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: house-prices-app
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jmr96registry.azurecr.io/flask_api_house_prices_backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: house-prices-app-config
                  key: backend_port
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: house-prices-app-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: house-prices-app-config
                  key: postgres_password
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: house-prices-app-config
                  key: postgres_db
            - name: POSTGRES_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: house-prices-app-config
                  key: postgres_db_port
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: house-prices-app-config
                  key: postgres_db_host

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: house-prices-app
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: house-prices-app
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jmr96registry.azurecr.io/flask_api_house_prices_frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: FRONTEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: house-prices-app-config
                  key: frontend_port
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: house-prices-app-config
                  key: backend_port
            - name: HOST_NAME
              valueFrom:
                configMapKeyRef:
                  name: house-prices-app-config
                  key: backend_service




---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: house-prices-app
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 9000
      targetPort: 4000

---
#
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ml-app-ingress
#  namespace: house-prices-app
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#spec:
#  rules:
#    - host: localhost
#      http:
#        paths:
#          - path: /(.*)
#            pathType: Prefix
#            backend:
#              service:
#                name: frontend-service
#                port:
#                  number: 9000





