# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: From Dockerfile, build and push to Azure registry and deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: frontend
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/flask_api_house_prices_frontend:${{ github.sha }}
        file: frontend/Dockerfile

#    - name: Build, tag, and push image to registry
#      env:
#        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        ECR_REPOSITORY: xxxxxxxx-report-api
#        IMAGE_TAG: latest
#      working-directory: apis/report-api
#      run: |
#        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Set the target Azure Kubernetes Service (AKS) cluster.
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: flask-api-house-prices
        resource-group: demo-rgr

#
#    # Create image pull secret for ACR
#    - uses: azure/k8s-create-secret@v1
#      with:
#        container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
#        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
#        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#        secret-name: ${{ env.SECRET }}
#        namespace: ${{ env.NAMESPACE }}
#        force: true
#
#    # Deploy app to AKS
#    - uses: azure/k8s-deploy@v1
#      with:
#        manifests: |
#          manifests/deployment.yml
#          manifests/service.yml
#        images: |
#          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
#        imagepullsecrets: |
#          ${{ env.SECRET }}
#        namespace: ${{ env.NAMESPACE }}