# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: From Dockerfile, build and push to Azure registry and deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: 'ubuntu-latest'

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: frontend
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/flask_api_house_prices_frontend:${{ github.sha }}
        file: frontend/Dockerfile

#    - name: Build, tag, and push image to registry
#      env:
#        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        ECR_REPOSITORY: xxxxxxxx-report-api
#        IMAGE_TAG: latest
#      working-directory: apis/report-api
#      run: |
#        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


    ############DEPLOY TO AKS#############
    # Set the target Azure Kubernetes Service (AKS) cluster.
    - name: Azure Kubernetes set context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: flask-api-house-prices
        resource-group: demo-rgr

#
#    # Create K8S secret to pull image
    - name: Create secret in Kubernetes cluster
      uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: docker-image-pull-secret
        namespace: house-prices-app
#
    # Deploy app to AKS
    - name: Deploy to Kubernetes cluster
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          k8s_deployment/deployment.yaml
        images: |
          ${{ secrets.REGISTRY_LOGIN_SERVER }}/flask_api_house_prices_frontend:${{ github.sha }}
        imagepullsecrets: |
          docker-image-pull-secret
        namespace: house-prices-app
        action: deploy